import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/ui/Navigation";
import App from "@/components/ui/App";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body
                className={
                    // inter.className +
                    " bg-background flex flex-col min-h-screen"
                }
            >
                <App>
                    <Navigation />
                    {children}
                </App>
                <div id="modal-root"></div>
            </body>
        </html>
    );
}
